#!/usr/bin/env python3
"""Generate Xcode settings from .env without printing or executing its contents."""
from pathlib import Path
import re

root = Path(__file__).resolve().parents[1]
env = root / ".env"
if not env.exists():
    raise SystemExit("Copy .env.example to .env and set GEMINI_API_KEY first.")
values = {}
for line in env.read_text().splitlines():
    line = line.strip()
    if not line or line.startswith("#"):
        continue
    key, sep, value = line.partition("=")
    if not sep:
        raise SystemExit("Invalid .env assignment.")
    values[key.strip()] = value.strip().strip("\"'")
key = values.get("GEMINI_API_KEY", "")
if key == "YOUR_GEMINI_API_KEY" or not re.fullmatch(r"[A-Za-z0-9_-]+", key):
    raise SystemExit("GEMINI_API_KEY is missing or has unsupported characters.")
target = root / "Config" / "Secrets.xcconfig"
target.parent.mkdir(exist_ok=True)
target.write_text("// Generated by Scripts/configure.py; do not commit.\nGEMINI_API_KEY = " + key + "\n")
target.chmod(0o600)
print("Generated local Xcode configuration. API key was not printed.")
